config/routes.rb
Rails.application.routes.draw do
  resources :inventory_files
  resources :inventories, only: [:index, :show]
end

app/models/inventory_file.rb
class InventoryFile < ApplicationRecord
  has_many :inventories, dependent: :destroy
  has_many :items, through: :inventories
  belongs_to :user
  belongs_to :shelf, optional: true

  if ENV['ENJU_STORAGE'] == 's3'
    has_attached_file :inventory, storage: :s3,
                                  s3_credentials: {
        access_key: ENV['AWS_ACCESS_KEY_ID'],
        secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
        bucket: ENV['S3_BUCKET_NAME']
      },
                                  s3_permissions: :private
  else
    has_attached_file :inventory,
      path: ":rails_root/private/system/:class/:attachment/:id_partition/:style/:filename"
  end
  validates_attachment_content_type :inventory, content_type: ['text/csv', 'text/plain', 'text/tab-separated-values']
  validates_attachment_presence :inventory, on: :create
  attr_accessor :library_id

  paginates_per 10

  def import
    if ENV['ENJU_STORAGE'] == 's3'
      body = Faraday.get(inventory.expiring_url(10)).body.force_encoding('UTF-8')
    else
      body = File.open(inventory.path).read
    end

    CSV.parse(body, headers: true, col_sep: "\t") do |row|
      # 電子書籍を除外
      next if row['shelf'] == 'web'
      item_identifier = row['item_identifier'].to_s.strip
      next if item_identifier.blank?

      Item.transaction do
        item = Item.find_by(item_identifier: item_identifier)
        Inventory.create(
          inventory_file: self,
          item: item,
          current_shelf_name: shelf.name,
          item_identifier: item_identifier
        )

        next unless item

        # 配架場所の変更を反映
        unless row['current_shelf'] == row['shelf']
          unless row['current_shelf'] == '-' or row['current_shelf'].blank?
            shelf = Shelf.find_by(name: row['current_shelf'])
            if item && shelf
              item.update!(shelf: Shelf.find_by(name: row['current_shelf']))
              Rails.logger.info "Inventory: #{item.item_identifier}: shelf updated to #{shelf.name}"
            end
          end
        end
        next

        case row['circulation_status']
        when 'On Loan'
          # 書架にないと報告されたが、確認したら貸出中の場合、不明日を削除
          if item.missing_since.present?
            item.update!(missing_since: nil)
            Rails.logger.info "Inventory: #{row['item_identifier']}: wrong report (rent)"
          end
        when 'Available On Shelf'
          # 書架にないと報告されたが、確認したら書架にあった本を「利用可能」に変更
          if row['current_shelf'] == '-' or row['current_shelf'].blank?
            if item.missing_since.present? && !item.rent?
              item.update!(missing_since: nil, circulation_status: CirculationStatus.find_by(name: row['circulation_status']))
              Rails.logger.info "Inventory: #{row['item_identifier']}: wrong report (on shelf)"
            end
          end

          # 発見された不明本の状態を変更
          unless row['current_shelf'] == '-' or row['current_shelf'].blank?
            if row['found_at'].present?
              if item.rent?
                item.update!(missing_since: nil)
              else
                item.update!(
                  missing_since: nil,
                  circulation_status: CirculationStatus.find_by(name: row['circulation_status'])
                )
              end
              Rails.logger.info "Inventory: #{row['item_identifier']}: changed status to found"
            end
          end

          if item.circulation_status.name == 'In Process'
            item.update!(circulation_status: CirculationStatus.find_by(name: 'Available On Shelf'))
            Rails.logger.info "Inventory: #{row['item_identifier']}: changed status to available"
          end
        when 'Missing'
          item.circulation_status = CirculationStatus.find_by(name: 'Missing') unless item.circulation_status == 'Missing'
          if row['missing_since'].blank?
            item.update!(missing_since: Date.today)
            Rails.logger.info "Inventory: #{row['item_identifier']}: changed status to missing"
          else
            item.update!(missing_since: Date.parse(row['missing_since']))
            Rails.logger.info "Inventory: #{row['item_identifier']}: changed status to missing"
          end
        end
      end
    end
  end

  def export(col_sep: "\t")
    file = Tempfile.create('inventory_file') do |f|
      inventories.each do |inventory|
        f.write inventory.to_hash.values.to_csv(col_sep)
      end

      f.rewind
      f.read
    end

    file
  end

  def missing_items
    Item.where(Inventory.where('items.id = inventories.item_id AND inventories.inventory_file_id = ?', id).exists.not)
  end

  def found_items
    items
  end
end

# == Schema Information
#
# Table name: inventory_files
#
#  id                     :integer          not null, primary key
#  filename               :string
#  content_type           :string
#  size                   :integer
#  user_id                :integer
#  note                   :text
#  created_at             :datetime
#  updated_at             :datetime
#  inventory_file_name    :string
#  inventory_content_type :string
#  inventory_file_size    :integer
#  inventory_updated_at   :datetime
#  inventory_fingerprint  :string
#  shelf_id               :integer
#

app/controllers/inventory_files_controller.rb
class InventoryFilesController < ApplicationController
  before_action :set_inventory_file, only: [:show, :edit, :update, :destroy]
  before_action :check_policy, only: [:index, :new, :create]
  before_action :prepare_options, only: [:new, :edit]

  # GET /inventory_files
  # GET /inventory_files.json
  def index
    @inventory_files = InventoryFile.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inventory_files }
    end
  end

  # GET /inventory_files/1
  # GET /inventory_files/1.json
  def show
    @inventories = @inventory_file.inventories.page(params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @inventory_file }
      format.download {
        send_data @inventory_file.inventory.download, filename: @inventory_file.inventory.filename.to_s, type: @inventory_file.inventory.content_type, disposition: disposition
      }
    end
  end

  # GET /inventory_files/new
  # GET /inventory_files/new.json
  def new
    @inventory_file = InventoryFile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @inventory_file }
    end
  end

  # GET /inventory_files/1/edit
  def edit
  end

  # POST /inventory_files
  # POST /inventory_files.json
  def create
    @inventory_file = InventoryFile.new(inventory_file_params)
    @inventory_file.user = current_user

    respond_to do |format|
      if @inventory_file.save
        flash[:notice] = t('controller.successfully_created', model: t('activerecord.models.inventory_file'))
        # @inventory_file.import
        format.html { redirect_to(@inventory_file) }
        format.json { render json: @inventory_file, status: :created, location: @inventory_file }
      else
        prepare_options
        format.html { render action: "new" }
        format.json { render json: @inventory_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /inventory_files/1
  # PUT /inventory_files/1.json
  def update
    respond_to do |format|
      if @inventory_file.update(inventory_file_params)
        flash[:notice] = t('controller.successfully_updated', model: t('activerecord.models.inventory_file'))
        format.html { redirect_to(@inventory_file) }
        format.json { head :no_content }
      else
        prepare_options
        format.html { render action: "edit" }
        format.json { render json: @inventory_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_files/1
  # DELETE /inventory_files/1.json
  def destroy
    @inventory_file.destroy

    respond_to do |format|
      format.html { redirect_to inventory_files_url }
      format.json { head :no_content }
    end
  end

  private
  def set_inventory_file
    @inventory_file = InventoryFile.find(params[:id])
    authorize @inventory_file
  end

  def check_policy
    authorize InventoryFile
  end

  def prepare_options
    @libraries = Library.order(:position)
    @shelves = Shelf.order(:position)
  end

  def inventory_file_params
    params.require(:inventory_file).permit(:inventory, :shelf_id, :note)
  end
end

app/views/inventory_files/_form.html.erb
<%= form_for(@inventory_file) do |f| -%>
  <%= f.error_messages -%>

  <div class="field">
    <%= f.label "#{t('activerecord.models.library')} / #{t('activerecord.models.shelf')}" -%>
    <%= f.select :library_id, @libraries.map{|l| [l.display_name, l.id]} %>
    <%= f.select :shelf_id, @shelves.map{|s| [s.display_name, s.id]} %>
    <%= render 'observe_field' %>
  </div>

  <div class="field">
    <%= f.label t('page.file') -%><br />
    <%= f.file_field :inventory -%>
  </div>

  <div class="field">
    <%= f.label :note -%> <br />
    <%= f.text_area :note -%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<%- end -%>

app/views/inventory_files/_observe_field.html.erb
<script type="text/javascript">
  function displayVals() {
    var libraryValue = $("#inventory_file_library_id").val();
    $("#inventory_file_shelf_id").load('<%= shelves_path %>?mode=select&library_id=' + libraryValue);
  }
  $("#inventory_file_library_id").change(displayVals);
</script>

app/views/inventory_files/_results.html.erb
<h2><%= t('activerecord.models.inventory') %></h2>

<p>
  <%= link_to((image_tag 'icons/page_white_excel.png', size: '16x16', alt: 'TSV', class: 'enju_icon'), inventories_path(inventory_file_id: @inventory_file.id, format: :text)) -%>
  (<%= link_to 'TSV', inventories_path(inventory_file_id: @inventory_file.id, format: :text) -%>)
</p>

<table class="table table-striped index">
  <tr>
    <th><%= t('activerecord.attributes.inventory.lineno') %></th>
    <th><%= t('activerecord.attributes.inventory.current_shelf_name') %></th>
    <th><%= t('activerecord.attributes.inventory.item_identifier') %></th>
    <th><%= t('activerecord.models.manifestation') %></th>
    <th></th>
  </tr>
<% @inventories.each_with_index do |inventory, idx| %>
  <tr class="line<%= cycle("0", "1") -%>">
    <td><%= @inventories.offset_value + idx + 1 %></td>
    <td><%= inventory.current_shelf_name %></td>
    <td><%= inventory.item_identifier %></td>
    </td>
    <td>
      <% if inventory.item %>
        <%= link_to inventory.item.item_identifier, inventory.item %>
        <br />
        <%= link_to inventory.item.manifestation.original_title, inventory.item.manifestation if inventory.item.try(:manifestation) %>
      <% end %>
    </td>
    <td>
      <%= link_to t('page.show'), inventory %>
      <%= link_to t('page.destroy'), inventory, data: {confirm: t('page.are_you_sure')}, method: :delete %>
    </td>
  </tr>
<% end %>
</table>
<%= paginate(@inventories) %>

app/views/inventory_files/edit.html.erb
<div id="content_detail" class="ui-corner-all ui-widget-content">
  <h1 class="title"><%= t('page.editing', :model => t('activerecord.models.inventory_file')) -%></h1>
  <div id="content_list">

    <%= render 'form' %>

  </div>
</div>

<div id="submenu" class="ui-corner-all ui-widget-content">
  <ul>
    <li><%= link_to t('page.show'), @inventory_file -%></li>
    <li><%= link_to t('page.back'), inventory_files_path -%></li>
  </ul>
</div>

app/views/inventory_files/index.html.erb
<div id="content_detail" class="ui-corner-all ui-widget-content">
<h1 class="title"><%= t('page.listing', :model => t('activerecord.models.inventory_file')) -%></h1>
<div id="content_list">

<table class="table table-striped index">
  <tr>
    <th><%= t('activerecord.attributes.inventory_file.shelf') -%> </th>
    <th><%= t('activerecord.attributes.inventory_file.inventory_file_name') -%> </th>
    <th><%= t('activerecord.attributes.inventory_file.inventory_file_size') -%> </th>
    <th><%= t('activerecord.models.user') -%> </th>
    <th></th>
  </tr>

<%- @inventory_files.each do |inventory_file| -%>
  <tr class="line<%= cycle("0", "1") -%>">
    <td><%= link_to inventory_file.shelf.display_name, inventory_file.shelf %></td>
    <td>
      <%= link_to inventory_file.inventory_file_name, inventory_file -%>
      <br />
      <%= inventory_file.created_at -%>
    </td>
    <td><%= inventory_file.inventory_file_size -%> </td>
    <td><%= link_to inventory_file.user.username, inventory_file.user.profile if inventory_file.user.try(:profile) -%> </td>
    <td>
      <%= link_to t('page.edit'), edit_inventory_file_path(inventory_file) -%>
      <%= link_to t('page.destroy'), inventory_file, :data => {:confirm => t('page.are_you_sure')}, :method => :delete -%>
    </td>
  </tr>
<%- end -%>
</table>

<%= paginate(@inventory_files) -%>
</div>
</div>

<div id="submenu" class="ui-corner-all ui-widget-content">
  <ul>
    <li><%= link_to t('page.new', :model => t('activerecord.models.inventory_file')), new_inventory_file_path -%></li>
  </ul>
</div>

app/views/inventory_files/new.html.erb
<div id="content_detail" class="ui-corner-all ui-widget-content">
  <h1 class="title"><%= t('page.new', :model => t('activerecord.models.inventory_file')) -%> </h1>
  <div id="content_list">

    <%= render 'form' %>

  </div>
</div>

<div id="submenu" class="ui-corner-all ui-widget-content">
  <ul>
    <li><%= link_to t('page.back'), inventory_files_path -%> </li>
  </ul>
</div>

app/views/inventory_files/show.html.erb
<div id="content_detail" class="ui-corner-all ui-widget-content">
  <h1 class="title"><%= t('page.showing', :model => t('activerecord.models.inventory_file')) -%></h1>
  <div id="content_list">
    <p id="notice"><%= notice %></p>

    <p>
      <strong><%= t('activerecord.attributes.inventory_file.shelf') -%> :</strong>
      <%= link_to @inventory_file.shelf.display_name, @inventory_file.shelf -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.inventory_file.inventory_file_name') -%> :</strong>
      <%= @inventory_file.inventory_file_name -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.inventory_file.inventory_content_type') -%> :</strong>
      <%= @inventory_file.inventory_content_type -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.inventory_file.inventory_file_size') -%> :</strong>
      <%= @inventory_file.inventory_file_size -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.inventory_file.inventory_fingerprint') -%> :</strong>
      <%= @inventory_file.inventory_fingerprint -%>
    </p>

    <p>
      <strong><%= t('activerecord.models.user') -%> :</strong>
      <%= link_to @inventory_file.user.username, @inventory_file.user.profile if @inventory_file.user.try(:profile) -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.inventory_file.note') -%> :</strong>
      <%= @inventory_file.note -%>
    </p>

    <% if @inventories %>
      <%= render 'results' %>
    <% end %>

  </div>
</div>

<div id="submenu" class="ui-corner-all ui-widget-content">
  <ul>
    <li><%= link_to t('page.edit'), edit_inventory_file_path(@inventory_file) -%> </li>
    <li><%= back_to_index(flash[:page_info]) -%> </li>
  </ul>
</div>