config/routes.rb
Rails.application.routes.draw do
  resources :inventory_files
  resources :inventories, only: [:index, :show]
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :item, optional: true
  belongs_to :inventory_file

  validates :item_identifier, :current_shelf_name, presence: true
  validates :item_id, :item_identifier, uniqueness: {scope: :inventory_file_id}

  paginates_per 10

  def to_hash
    {
      created_at: created_at,
      identifier: item_identifier,
      item_identifier: item.try(:item_identifier),
      current_shelf: current_shelf_name,
      shelf: item.try(:shelf),
      call_number: item.try(:call_number),
      circulation_status: item.try(:circulation_status).try(:name),
      title: item.try(:manifestation).try(:original_title),
      extent: item.try(:manifestation).try(:extent)
    }
  end

  def lost
    item.circulation_status = CirculationStatus.find_by(name: 'Missing')
  end

  def found
    if item.rended?
      item.circulation_status = CirculationStatus.find_by(name: 'On Loan')
    else
      item.circulation_status = CirculationStatus.find_by(name: 'Available On Shelf')
    end
  end
end

# == Schema Information
#
# Table name: inventories
#
#  id                 :integer          not null, primary key
#  item_id            :integer
#  inventory_file_id  :integer
#  note               :text
#  created_at         :datetime
#  updated_at         :datetime
#  item_identifier    :string
#  current_shelf_name :string
#

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]
  before_action :check_policy, only: [:index, :new, :create]

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inventories }
    end
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @inventory }
    end
  end

  private
  def set_inventory
    @inventory = Inventory.find(params[:id])
    authorize @inventory
  end

  def check_policy
    authorize Inventory
  end

  def inventory_params
    params.require(:inventory).permit(
      :item_id, :inventory_id, :note
    )
  end
end

app/views/inventories/edit.html.erb
<div id="content_detail" class="ui-corner-all ui-widget-content">
<h1 class="title"><%= t('page.editing', :model => t('activerecord.models.inventory')) -%> </h1>
<div id="content_list">

<%= form_for(@inventory) do |f| -%>
  <%= f.error_messages -%>

  <div class="field">
    <%= f.label :item_id -%><br />
    <%= f.text_field :item_id -%>
  </div>
  <div class="field">
    <%= f.label :inventory_file_id -%><br />
    <%= f.text_field :inventory_file_id -%>
  </div>
  <div class="field">
    <%= f.label :note -%><br />
    <%= f.text_area :note -%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<%- end -%>

</div>
</div>

<div id="submenu" class="ui-corner-all ui-widget-content">
  <ul>
    <li><%= link_to t('page.show'), @inventory -%></li>
    <li><%= link_to t('page.back'), inventories_path -%></li>
  </ul>
</div>

app/views/inventories/index.html.erb
<div id="content_detail" class="ui-corner-all ui-widget-content">
<h1 class="title"><%= t('page.listing', :model => t('activerecord.models.inventory')) -%></h1>
<div id="content_list">

<table class="table table-striped index">
  <tr>
    <th><%= t('activerecord.models.inventory_file') -%> </th>
    <th><%= t('activerecord.models.item') -%> </th>
    <th></th>
  </tr>

<%- @inventories.each do |inventory| -%>
  <tr class="line<%= cycle("0", "1") -%>">
    <td><%= link_to inventory.inventory_file_id, inventory.inventory_file -%></td>
    <td><%= link_to inventory.item.item_identifier, inventory.item -%></td>
    <td>
      <%= link_to t('page.show'), inventory -%>
      <%= link_to t('page.edit'), edit_inventory_path(inventory) -%>
      <%= link_to t('page.destroy'), inventory, :data => {:confirm => t('page.are_you_sure')}, :method => :delete -%>
    </td>
  </tr>
<%- end -%>
</table>

<%= paginate(@inventories) -%>

</div>
</div>

<div id="submenu" class="ui-corner-all ui-widget-content">
  <ul>
    <li><%= link_to t('page.new', :model => t('activerecord.models.inventory')), new_inventory_path -%></li>
  </ul>
</div>

app/views/inventories/new.html.erb
<div id="content_detail" class="ui-corner-all ui-widget-content">
<h1 class="title"><%= t('page.new', :model => t('activerecord.models.inventory')) -%> </h1>
<div id="content_list">

<%= form_for(@inventory) do |f| -%>
  <%= f.error_messages -%>

  <div class="field">
    <%= f.label :item_id -%> <br />
    <%= f.text_field :item_id -%>
  </div>
  <div class="field">
    <%= f.label :inventory_file_id -%> <br />
    <%= f.text_field :inventory_file_id -%>
  </div>
  <div class="field">
    <%= f.label :note -%> <br />
    <%= f.text_area :note -%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<%- end -%>

</div>
</div>

<div id="submenu" class="ui-corner-all ui-widget-content">
  <ul>
    <li><%= link_to t('page.back'), inventories_path -%></li>
  </ul>
</div>

app/views/inventories/show.html.erb
<div id="content_detail" class="ui-corner-all ui-widget-content">
<h1 class="title"><%= t('page.showing', :model => t('activerecord.models.inventory')) -%> </h1>
<div id="content_list">
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('activerecord.models.item') -%>:</strong>
  <%= link_to @inventory.item.item_identifier, @inventory.item -%>
</p>

<p>
  <strong><%= t('activerecord.models.inventory_file') -%>:</strong>
  <%= link_to @inventory.inventory_file.id, @inventory.inventory_file -%>
</p>

<p>
  <strong><%= t('activerecord.attributes.inventory.note') -%>:</strong>
  <%= @inventory.note -%>
</p>

</div>
</div>

<div id="submenu" class="ui-corner-all ui-widget-content">
  <ul>
    <li><%= link_to t('page.edit'), edit_inventory_path(@inventory) -%></li>
    <li><%= back_to_index(flash[:page_info]) -%></li>
  </ul>
</div>